#
# prj.conf - Application configuration
#

# Console / UART
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y

# Kernel
CONFIG_NEWLIB_LIBC=n
CONFIG_PRINTK=y

# Reduce footprint
CONFIG_MINIMAL_LIBC=y
CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC=48000000
